language:
- node_js
node_js:
- '8.11'
cache:
  directories:
  - node_modules
script:
- yarn global add codecov -g
- yarn test --coverage && codecov
- yarn run build
before_install:
- openssl aes-256-cbc -K $encrypted_3d04314fb491_key -iv $encrypted_3d04314fb491_iv
  -in deployf_rsa.enc -out deployf_rsa -d
before_deploy:
    - eval "$(ssh-agent -s)"
    - mkdir -p ~/.ssh  &&  echo "Host *" > ~/.ssh/config && echo " StrictHostKeyChecking
      no" >> ~/.ssh/config
    - chmod 600 deployf_rsa
deploy:
    provider: script
    skip_cleanup: true
    script: rsync -r --delete-after -e "ssh -i deployf_rsa -p $server_port" $TRAVIS_BUILD_DIR/build/
        $server_user@$server_ip:/home/example/www/articleapp
    on:
        branch: master
        