language:
- node_js
node_js:
- '8.11'
cache:
  directories:
  - node_modules
script:
- yarn global add codecov -g
- yarn test --coverage && codecov
- yarn run build
before_install:
- openssl aes-256-cbc -K $encrypted_3d04314fb491_key -iv $encrypted_3d04314fb491_iv
  -in deployf_rsa.enc -out deployf_rsa -d
